### ISSUE TITLE
Recent errors with chocolatey 1.2.0

### ISSUE THREAD

**Issue by piponazo** [egor-tensin/setup-cygwin#9] opened 2022-11-01 12:45 UTC
Hi!

I am using this Github action for the Exiv2 project. Few days ago I noticed that the Cygwin builds started to fail, and when I compare the failing jobs:
https://github.com/Exiv2/exiv2/actions/runs/3365823530/jobs/5585304895
With the non failing ones from 1 week ago:
https://github.com/Exiv2/exiv2/actions/runs/3332745648/jobs/5513973618

The only different that I see is that apparently chocolatey got upgraded from version 1.1.0 to 1.2.0.  The error is not very informative and just says this:

```
Chocolatey installed 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
The system cannot find the file specified
Error: Process completed with exit code 1.
```

The pipeline can be found here: https://github.com/Exiv2/exiv2/blob/dc5dc0d2e39aba87e38cda8378ffd90b833877a6/.github/workflows/on_PR_windows_matrix.yml#L165

Do you know what could be happening? Or any other feedback that could help me to fix this situation?

Thanks in advance for your time and for this nice github action :)

**Comment by FGasper** [comment] 2022-11-01 14:00
Also happening for me: https://github.com/cpanel/p5-cPanel-APIClient/actions/runs/3369854268/jobs/5590289790

**Comment by gansm** [comment] 2022-11-02 00:46
Same here in my project:
https://github.com/gansm/finalcut/actions/runs/3347219222/jobs/5562942770

**Comment by michael-grunder** [comment] 2022-11-02 19:47
Same thing happening in hiredis:
https://github.com/redis/hiredis/actions/runs/3380340217/jobs/5613014442

**Comment by jkroepke** [comment] 2022-11-07 22:47
I have the same error, here is the error I got from the logs:

```
2022-11-07T22:35:19.3222967Z  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2022-11-07T22:35:19.3223386Z 2022-11-07 22:35:07,866 4196 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2022-11-07T22:35:19.3223687Z 2022-11-07 22:35:07,866 4196 [ERROR] - The system cannot find the file specified
2022-11-07T22:35:19.3224116Z 2022-11-07 22:35:07,897 4196 [ERROR] - More Details: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
2022-11-07T22:35:19.3224416Z    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
2022-11-07T22:35:19.3225014Z    at chocolatey.infrastructure.commands.CommandExecutor.execute_static(String process, String arguments, Int32 waitForExitInSeconds, String workingDirectory, Action`2 stdOutAction, Action`2 stdErrAction, Boolean updateProcessPath, Boolean allowUseWindow, Boolean waitForExit)
2022-11-07T22:35:19.3225565Z    at chocolatey.infrastructure.commands.CommandExecutor.execute(String process, String arguments, Int32 waitForExitInSeconds, String workingDirectory, Action`2 stdOutAction, Action`2 stdErrAction, Boolean updateProcessPath, Boolean allowUseWindow)
2022-11-07T22:35:19.3226040Z    at chocolatey.infrastructure.app.services.CygwinService.install_run(ChocolateyConfiguration config, Action`1 continueAction)
2022-11-07T22:35:19.3226552Z    at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
2022-11-07T22:35:19.3226948Z    at chocolatey.infrastructure.app.services.ChocolateyPackageService.install_run(ChocolateyConfiguration config)
2022-11-07T22:35:19.3227360Z    at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
2022-11-07T22:35:19.3227757Z    at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
2022-11-07T22:35:19.3227961Z    at chocolatey.console.Program.Main(String[] args)
```

https://github.com/jkroepke/helm-secrets/actions/runs/3414624012/jobs/5682825355

**Comment by gansm** [comment] 2022-11-28 16:18
This project seems to be dead, so I switched to [cygwin/cygwin-install-action](https://github.com/cygwin/cygwin-install-action).

Everything works as before:
https://github.com/gansm/finalcut/actions/runs/3566270301/jobs/5992496219

**Comment by chronoxor** [comment] 2022-11-28 16:34
> This project seems to be dead, so I switched to [cygwin/cygwin-install-action](https://github.com/cygwin/cygwin-install-action).
So did I

**Comment by yanorei32** [comment] 2023-01-02 04:58
@egor-tensin  
I confirmed this issue closed by v4!

example: https://github.com/yanorei32/VRChatRejoinTool/pull/40

I think this issue should probably be closed.

Thank you!

**Closed** 2023-01-02 10:13 UTC
